-- Agreement identifiers: UUID primary key + atomic integer sequence + text display number.
-- The sequence starts at 101 for a new installation and is advanced past any
-- existing Agreement#NNNNN values before it is used.
begin;

alter table public.agreements
  alter column id set default gen_random_uuid(),
  add column if not exists sequence_number integer,
  add column if not exists agreement_number text;

create sequence if not exists public.agreement_number_seq as integer start with 101;

select setval(
  'public.agreement_number_seq',
  greatest(
    100,
    coalesce((
      select max(
        case
          when agreement_number ~ '^Agreement#[0-9]+$'
            then substring(agreement_number from '[0-9]+$')::integer
          else sequence_number
        end
      )
      from public.agreements
    ), 100)
  ),
  true
);

create or replace function public.allocate_agreement_number()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  allocated integer;
begin
  -- Always allocate on insert. Client-provided temporary/timestamp identifiers
  -- are intentionally ignored, so concurrent inserts cannot collide.
  allocated := nextval('public.agreement_number_seq');
  new.sequence_number := allocated;
  new.agreement_number := 'Agreement#' || lpad(allocated::text, 5, '0');
  -- Some older deployments defined agreement_id itself as int4. That is the
  -- column which rejected values such as 20260730636225. Keep it sequential on
  -- those schemas; text-based legacy agreement_id columns are left untouched.
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'agreements'
      and column_name = 'agreement_id' and data_type = 'integer'
  ) then
    new := jsonb_populate_record(new, jsonb_build_object('agreement_id', allocated));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_allocate_agreement_number on public.agreements;
create trigger trg_allocate_agreement_number
before insert on public.agreements
for each row execute function public.allocate_agreement_number();

create unique index if not exists agreements_sequence_number_key
  on public.agreements(sequence_number);
create unique index if not exists agreements_agreement_number_key
  on public.agreements(agreement_number);

comment on column public.agreements.id is
  'Internal UUID primary key generated by PostgreSQL.';
comment on column public.agreements.sequence_number is
  'Database-allocated int4 sequence; never a timestamp or external reference.';
comment on column public.agreements.agreement_number is
  'Human-readable reference formatted as Agreement#NNNNN.';

commit;
